# Generated by Django 5.0.4 on 2024-04-28 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='VeaCanteen.product')),
                ('type', models.CharField(choices=[('Coffee', 'Coffee'), ('Juice', 'Juice'), ('Tea', 'Tea')], max_length=255)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=255)),
            ],
            bases=('VeaCanteen.product',),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='VeaCanteen.product')),
                ('type', models.CharField(choices=[('Bread', 'Bread'), ('Dessert', 'Dessert'), ('Salad', 'Salad'), ('WarmFood', 'Warm Food')], max_length=255)),
            ],
            bases=('VeaCanteen.product',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='VeaCanteen.product')),
            ],
        ),
    ]
