# Generated by Django 5.0.4 on 2024-04-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VeaCanteen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='drinks',
            field=models.ManyToManyField(to='VeaCanteen.drink'),
        ),
        migrations.AddField(
            model_name='order',
            name='food',
            field=models.ManyToManyField(to='VeaCanteen.food'),
        ),
    ]
