# Generated by Django 5.0.4 on 2024-04-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VeaCanteen', '0002_remove_order_products_order_drinks_order_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='order-existing', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
